version: '3.9'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - web
      - db
  db:
    image: "docker.io/library/postgres:13.1-alpine"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db-data:
